### ISSUE TITLE
`analyte` in schema

### ISSUE THREAD

**Issue by YWAN446** [shedding-hub/shedding-hub#86]
Hi @tillahoffmann, Youwei encountered some issues today when using `analyte` instead of `analytes` in the YAML file. See PR#85. The validation failed with the log https://github.com/shedding-hub/shedding-hub/actions/runs/13253844170/job/36997045339. When she changed `analyte` to `analytes`, it passed. I think it could be the definition of `analyte` in the schema (see below).

![Image](https://github.com/user-attachments/assets/f7dda876-3be8-4fb9-af3a-49f298f5199d)

**Comment by tillahoffmann** [comment]
If there is a single analyte, the schema requires that there is no name because there only is one. So it would be

```yaml
analyte:
  description: ...
  limit_of_detection: ...
```

instead of

```yaml
analyte:
  [analyte name]:
    description: ...
    limit_of_detection: ...
```

I don't think we've used the single-analyte form much if at all. Maybe we should just drop that part of the schema and always use `analytes`. What do you think?
